movement_rules = {
  "INSTANT": {
    "Gem 1 (Level 1-1)": "Bounce Pads",
    "Gem 2 (Level 1-1)": "Wall Jump + Grapple Hook || Bounce Pads",
    "Gem 3 (Level 1-1)": "Wall Jump + Grapple Hook + Carrots + Slam",
    "Gem 4 (Level 1-1)": "Wall Jump + Grapple Hook + Balloons",
    "Gem 5 (Level 1-1)": "Wall Jump + Grapple Hook + Balloons + Bounce Pads",
    "Bonus Coin (Level 1-1)": "Wall Jump + Grapple Hook + Balloons",
    "Level Complete (Level 1-1)": "Wall Jump + Grapple Hook + Balloons + Bounce Pads",
    "Gem 1 (Level 1-2)": "Wall Jump + Grapple Hook + Climb || Bounce Pads",
    "Gem 2 (Level 1-2)": "Wall Jump + Balloons || Grapple Hook + Climb",
    "Gem 3 (Level 1-2)": "Wall Jump + Grapple Hook + Climb || Bounce Pads + Cannons",
    "Gem 4 (Level 1-2)": "Wall Jump + Grapple Hook + Climb + Cannons",
    "Gem 5 (Level 1-2)": "Wall Jump + Grapple Hook + Climb + Cannons + Slam + Carrots",
    "Level Complete (Level 1-2)": "Wall Jump + Grapple Hook + Climb + Cannons + Slam",
    "Gem 1 (Level 1-3)": "Bounce Pads + Grapple Hook",
    "Gem 2 (Level 1-3)": "Bounce Pads + Cannons + Balloons + Grapple Hook + Wall Jump + Swim",
    "Gem 3 (Level 1-3)": "Bounce Pads + Cannons + Balloons + Grapple Hook + Wall Jump + Swim",
    "Gem 4 (Level 1-3)": "Bounce Pads + Cannons + Balloons + Grapple Hook + Wall Jump + Swim + Slam",
    "Gem 5 (Level 1-3)": "Bounce Pads + Cannons + Balloons + Grapple Hook + Wall Jump + Swim + Slam",
    "Bonus Coin (Level 1-3)": "Bounce Pads + Cannons + Balloons + Grapple Hook + Wall Jump + Swim + Slam",
    "Level Complete (Level 1-3)": "Bounce Pads + Cannons + Balloons + Grapple Hook + Wall Jump + Swim + Slam",
    "Gem 1 (Level 1-4)": "Wall Jump + Grapple Hook + Balloons + Climb + Slam + Cannons",
    "Gem 2 (Level 1-4)": "Wall Jump + Grapple Hook + Balloons + Climb + Slam + Cannons + Bounce Pads",
    "Gem 3 (Level 1-4)": "Wall Jump + Grapple Hook + Balloons + Climb + Slam + Cannons + Bounce Pads",
    "Gem 4 (Level 1-4)": "Wall Jump + Grapple Hook + Balloons + Climb + Slam + Cannons + Bounce Pads",
    "Gem 5 (Level 1-4)": "Wall Jump + Grapple Hook + Balloons + Climb + Slam + Cannons + Bounce Pads",
    "Level Complete (Level 1-4)": "Wall Jump + Grapple Hook + Balloons + Climb + Slam + Cannons + Bounce Pads",
    "Gem 1 (Level 1-5)": "Grapple Hook + Wall Jump + Slam",
    "Gem 2 (Level 1-5)": "Grapple Hook + Wall Jump + Slam + Cannons + Swim",
    "Gem 3 (Level 1-5)": "Grapple Hook + Wall Jump + Slam + Cannons + Swim",
    "Gem 4 (Level 1-5)": "Grapple Hook + Wall Jump + Slam + Cannons + Swim + Climb || Damage Boost",
    "Gem 5 (Level 1-5)": "Grapple Hook + Wall Jump + Slam + Cannons + Swim + Climb",
    "Bonus Coin (Level 1-5)": "Grapple Hook + Wall Jump + Slam + Cannons + Swim",
    "Level Complete (Level 1-5)": "Grapple Hook + Wall Jump + Slam + Cannons + Swim + Climb",
    "Gem 1 (Level 1-B)": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Gem 2 (Level 1-B)": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Gem 3 (Level 1-B)": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Gem 4 (Level 1-B)": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Gem 5 (Level 1-B)": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Bonus Coin (Level 1-B)": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Beat REX": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Level Complete (Level 1-B)": "Slam + Grapple Hook + Balloons + Cannons + Wall Jump + Bounce Pads + Climb",
    "Gem 1 (Bonus 1-1)": "Wall Jump + Grapple Hook || Slam",
    "Gem 2 (Bonus 1-1)": "Wall Jump + Grapple Hook || Slam",
    "Gem 3 (Bonus 1-1)": "Wall Jump + Grapple Hook || Slam",
    "Gem 1 (Bonus 1-2)": "Grapple Hook",
    "Gem 2 (Bonus 1-2)": "Grapple Hook",
    "Gem 3 (Bonus 1-2)": "Grapple Hook",
    "Gem 1 (Bonus 1-3)": "Bounce Pads + Grapple Hook + Balloons",
    "Gem 2 (Bonus 1-3)": "Bounce Pads + Grapple Hook + Balloons",
    "Gem 3 (Bonus 1-3)": "Bounce Pads + Grapple Hook + Balloons",
    "Gem 1 (Bonus 1-4)": "Slam + Grapple Hook + Wall Jump",
    "Gem 2 (Bonus 1-4)": "Slam + Grapple Hook + Wall Jump",
    "Gem 3 (Bonus 1-4)": "Slam + Grapple Hook + Wall Jump",
    "Gem 1 (Level 2-1)": "Swim + Grapple Hook + Slam + Balloons",
    "Gem 2 (Level 2-1)": "Swim",
    "Gem 3 (Level 2-1)": "Swim + Wall Jump + Grapple Hook + Slam",
    "Gem 4 (Level 2-1)": "Swim + Wall Jump + Bounce Pads + Slam",
    "Gem 5 (Level 2-1)": "Swim + Wall Jump + Slam + Grapple Hook",
    "Bonus Coin (Level 2-1)": "Swim + Wall Jump + Slam",
    "Level Complete (Level 2-1)": "Swim + Wall Jump + Slam + Grapple Hook + Balloons",
    "Gem 1 (Level 2-2)": "Bounce Pads + Cannons + Wall Jump + Slam + Grapple Hook + Balloons",
    "Gem 2 (Level 2-2)": "Bounce Pads + Cannons + Wall Jump + Slam + Grapple Hook + Balloons",
    "Gem 3 (Level 2-2)": "Bounce Pads + Cannons + Wall Jump + Slam + Grapple Hook + Balloons",
    "Gem 4 (Level 2-2)": "Bounce Pads + Cannons + Wall Jump + Slam + Grapple Hook + Balloons",
    "Gem 5 (Level 2-2)": "Bounce Pads + Cannons + Wall Jump + Slam + Grapple Hook + Balloons",
    "Bonus Coin (Level 2-2)": "Bounce Pads + Cannons + Wall Jump + Slam + Grapple Hook + Balloons",
    "Level Complete (Level 2-2)": "Bounce Pads + Cannons + Wall Jump + Slam + Grapple Hook + Balloons",
    "Gem 1 (Level 2-3)": "Grapple Hook + Wall Jump",
    "Gem 2 (Level 2-3)": "Grapple Hook + Wall Jump + Slam",
    "Gem 3 (Level 2-3)": "Grapple Hook + Wall Jump + Slam + Swim",
    "Gem 4 (Level 2-3)": "Grapple Hook + Wall Jump + Slam + Swim",
    "Gem 5 (Level 2-3)": "Grapple Hook + Wall Jump + Slam + Swim",
    "Level Complete (Level 2-3)": "Grapple Hook + Wall Jump + Slam + Swim",
    "Gem 1 (Level 2-4)": "Wall Jump + Slam + Swim + Balloons || Damage Boost + Grapple Hook",
    "Gem 2 (Level 2-4)": "Wall Jump + Slam + Swim + Balloons + Grapple Hook",
    "Gem 3 (Level 2-4)": "Wall Jump + Slam + Swim + Wall Jump + Cannons + Grapple Hook",
    "Gem 4 (Level 2-4)": "Wall Jump + Slam + Swim + Balloons + Grapple Hook + Cannons",
    "Gem 5 (Level 2-4)": "Wall Jump + Slam + Swim + Balloons + Grapple Hook + Cannons",
    "Bonus Coin (Level 2-4)": "Wall Jump + Slam + Swim + Balloons + Grapple Hook + Cannons",
    "Level Complete (Level 2-4)": "Wall Jump + Slam + Swim + Balloons + Grapple Hook + Cannons",
    "Gem 1 (Level 2-5)": "Grapple Hook",
    "Gem 2 (Level 2-5)": "Grapple Hook",
    "Gem 3 (Level 2-5)": "Grapple Hook",
    "Gem 4 (Level 2-5)": "Grapple Hook + Wall Jump",
    "Gem 5 (Level 2-5)": "Grapple Hook + Wall Jump",
    "Bonus Coin (Level 2-5)": "Grapple Hook",
    "Level Complete (Level 2-5)": "Grapple Hook + Wall Jump",
    "Gem 1 (Level 2-B)": "Swim + Slam",
    "Gem 2 (Level 2-B)": "Swim + Slam + Bounce Pads + Wall Jump",
    "Gem 3 (Level 2-B)": "Swim + Slam + Bounce Pads + Wall Jump",
    "Gem 4 (Level 2-B)": "Swim + Slam + Bounce Pads + Wall Jump + Cannons + Grapple Hook",
    "Gem 5 (Level 2-B)": "Swim + Slam + Bounce Pads + Wall Jump + Cannons + Grapple Hook",
    "Level Complete (Level 2-B)": "Swim + Slam + Bounce Pads + Wall Jump + Cannons + Grapple Hook + Balloons",
    "Beat TANK": "Swim + Slam + Bounce Pads + Wall Jump + Cannons + Grapple Hook + Balloons",
    "Gem 1 (Bonus 2-1)": "Swim",
    "Gem 2 (Bonus 2-1)": "Swim",
    "Gem 3 (Bonus 2-1)": "Swim",
    "Gem 1 (Bonus 2-2)": "Bounce Pads + Wall Jump + Climb + Grapple Hook + Balloons",
    "Gem 2 (Bonus 2-2)": "Bounce Pads + Wall Jump + Climb + Grapple Hook + Balloons",
    "Gem 3 (Bonus 2-2)": "Bounce Pads + Wall Jump + Climb + Grapple Hook + Balloons",
    "Gem 1 (Bonus 2-3)": "Wall Jump + Climb + Swim",
    "Gem 2 (Bonus 2-3)": "Wall Jump + Climb + Swim",
    "Gem 3 (Bonus 2-3)": "Wall Jump + Climb + Swim",
    "Gem 1 (Bonus 2-4)": "Swim + Wall Jump || Cannons + Grapple Hook",
    "Gem 2 (Bonus 2-4)": "Swim + Wall Jump || Cannons + Grapple Hook",
    "Gem 3 (Bonus 2-4)": "Swim + Wall Jump || Cannons + Grapple Hook",
    "Gem 1 (Level 3-1)": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Gem 2 (Level 3-1)": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Gem 3 (Level 3-1)": "Wall Jump + Grapple Hook + Balloons || Damage Boost + Cannons",
    "Gem 4 (Level 3-1)": "Wall Jump + Grapple Hook + Cannons",
    "Gem 5 (Level 3-1)": "Wall Jump + Grapple Hook + Cannons",
    "Bonus Coin (Level 3-1)": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level Complete (Level 3-1)": "Wall Jump + Grapple Hook + Cannons",
    "Gem 1 (Level 3-2)": "Bounce Pads + Grapple Hook",
    "Gem 2 (Level 3-2)": "Bounce Pads + Grapple Hook + Cannons + Balloons || Damage Boost",
    "Gem 3 (Level 3-2)": "Bounce Pads + Grapple Hook + Cannons + Balloons + Wall Jump",
    "Gem 4 (Level 3-2)": "Bounce Pads + Grapple Hook + Cannons + Balloons + Wall Jump",
    "Gem 5 (Level 3-2)": "Bounce Pads + Grapple Hook + Cannons + Balloons + Wall Jump",
    "Level Complete (Level 3-2)": "Bounce Pads + Grapple Hook + Cannons + Balloons + Wall Jump",
    "Gem 1 (Level 3-3)": "Slam + Bounce Pads + Grapple Hook + Wall Jump",
    "Gem 2 (Level 3-3)": "Slam + Bounce Pads + Grapple Hook + Wall Jump + Climb + Balloons",
    "Gem 3 (Level 3-3)": "Slam + Bounce Pads + Grapple Hook + Wall Jump + Climb + Balloons",
    "Gem 4 (Level 3-3)": "Slam + Bounce Pads + Grapple Hook + Wall Jump + Balloons + Swim",
    "Gem 5 (Level 3-3)": "Slam + Bounce Pads + Grapple Hook + Wall Jump + Climb + Balloons + Swim",
    "Bonus Coin (Level 3-3)": "Slam + Bounce Pads + Grapple Hook + Wall Jump + Balloons",
    "Level Complete (Level 3-3)": "Slam + Bounce Pads + Grapple Hook + Wall Jump + Climb + Balloons + Swim",
    "Gem 1 (Level 3-4)": "Grapple Hook + Bounce Pads + Wall Jump + Swim",
    "Gem 2 (Level 3-4)": "Grapple Hook + Bounce Pads + Wall Jump + Swim",
    "Gem 3 (Level 3-4)": "Grapple Hook + Bounce Pads + Wall Jump + Swim + Balloons + Cannons",
    "Gem 4 (Level 3-4)": "Grapple Hook + Bounce Pads + Wall Jump + Swim + Balloons + Cannons",
    "Gem 5 (Level 3-4)": "Grapple Hook + Bounce Pads + Wall Jump + Swim + Balloons + Cannons",
    "Bonus Coin (Level 3-4)": "Grapple Hook + Bounce Pads + Wall Jump + Swim",
    "Level Complete (Level 3-4)": "Grapple Hook + Bounce Pads + Wall Jump + Swim + Balloons + Cannons",
    "Gem 1 (Level 3-5)": "Slam + Balloons + Grapple Hook + Bounce Pads",
    "Gem 2 (Level 3-5)": "Slam + Balloons + Grapple Hook + Bounce Pads",
    "Gem 3 (Level 3-5)": "Slam + Balloons + Grapple Hook + Bounce Pads + Wall Jump",
    "Gem 4 (Level 3-5)": "Slam + Balloons + Grapple Hook + Bounce Pads + Wall Jump",
    "Gem 5 (Level 3-5)": "Slam + Balloons + Grapple Hook + Bounce Pads + Wall Jump",
    "Bonus Coin (Level 3-5)": "Slam + Balloons + Grapple Hook + Bounce Pads",
    "Level Complete (Level 3-5)": "Slam + Balloons + Grapple Hook + Bounce Pads + Wall Jump",
    "Gem 1 (Level 3-B)": "Cannons + Wall Jump + Grapple Hook",
    "Gem 2 (Level 3-B)": "Cannons + Wall Jump + Grapple Hook",
    "Gem 3 (Level 3-B)": "Cannons + Wall Jump + Grapple Hook",
    "Gem 4 (Level 3-B)": "Cannons + Wall Jump + Grapple Hook",
    "Gem 5 (Level 3-B)": "Cannons + Wall Jump + Grapple Hook",
    "Level Complete (Level 3-B)": "Cannons + Wall Jump + Grapple Hook",
    "Beat FACE": "Cannons + Wall Jump + Grapple Hook",
    "Gem 1 (Bonus 3-1)": "Wall Jump + Grapple Hook",
    "Gem 2 (Bonus 3-1)": "Wall Jump + Grapple Hook",
    "Gem 3 (Bonus 3-1)": "Wall Jump + Grapple Hook",
    "Gem 1 (Bonus 3-2)": "Grapple Hook + Cannons + Balloons + Wall Jump + Bounce Pads",
    "Gem 2 (Bonus 3-2)": "Grapple Hook + Cannons + Balloons + Wall Jump + Bounce Pads",
    "Gem 3 (Bonus 3-2)": "Grapple Hook + Cannons + Balloons + Wall Jump + Bounce Pads",
    "Gem 1 (Bonus 3-3)": "Grapple Hook + Wall Jump + Climb",
    "Gem 2 (Bonus 3-3)": "Grapple Hook + Wall Jump + Climb",
    "Gem 3 (Bonus 3-3)": "Grapple Hook + Wall Jump + Climb",
    "Gem 1 (Bonus 3-4)": "Grapple Hook + Wall Jump + Bounce Pads + Balloons",
    "Gem 2 (Bonus 3-4)": "Grapple Hook + Wall Jump + Bounce Pads + Balloons",
    "Gem 3 (Bonus 3-4)": "Grapple Hook + Wall Jump + Bounce Pads + Balloons",
    "Gem 1 (Level 4-1)": "Grapple Hook",
    "Gem 2 (Level 4-1)": "Grapple Hook + Balloons + Wall Jump",
    "Gem 3 (Level 4-1)": "Grapple Hook + Balloons + Wall Jump",
    "Gem 4 (Level 4-1)": "Grapple Hook + Balloons + Wall Jump",
    "Gem 5 (Level 4-1)": "Grapple Hook + Balloons + Wall Jump",
    "Level Complete (Level 4-1)": "Grapple Hook + Balloons + Wall Jump",
    "Gem 1 (Level 4-2)": "Wall Jump + Grapple Hook + Balloons",
    "Gem 2 (Level 4-2)": "Wall Jump + Grapple Hook + Cannons + Slam",
    "Gem 3 (Level 4-2)": "Wall Jump + Grapple Hook + Cannons + Slam",
    "Gem 4 (Level 4-2)": "Wall Jump + Grapple Hook + Cannons + Slam + Balloons",
    "Gem 5 (Level 4-2)": "Wall Jump + Grapple Hook + Cannons + Slam + Balloons",
    "Bonus Coin (Level 4-2)": "Wall Jump + Grapple Hook + Cannons",
    "Level Complete (Level 4-2)": "Wall Jump + Grapple Hook + Cannons + Slam + Balloons",
    "Gem 1 (Level 4-3)": "Grapple Hook + Wall Jump + Balloons + Climb + Cannons + Swim",
    "Gem 2 (Level 4-3)": "Grapple Hook + Wall Jump + Balloons + Climb + Cannons + Swim",
    "Gem 3 (Level 4-3)": "Grapple Hook + Wall Jump + Balloons + Climb + Cannons + Swim",
    "Gem 4 (Level 4-3)": "Grapple Hook + Wall Jump + Balloons + Climb + Cannons + Swim",
    "Gem 5 (Level 4-3)": "Grapple Hook + Wall Jump + Balloons + Climb + Cannons + Swim + Slam",
    "Bonus Coin (Level 4-3)": "Grapple Hook + Wall Jump + Balloons + Climb + Cannons + Swim",
    "Level Complete (Level 4-3)": "Grapple Hook + Wall Jump + Balloons + Climb + Cannons + Swim + Slam",
    "Gem 1 (Level 4-4)": "Wall Jump + Grapple Hook",
    "Gem 2 (Level 4-4)": "Wall Jump + Slam",
    "Gem 3 (Level 4-4)": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Gem 4 (Level 4-4)": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Gem 5 (Level 4-4)": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Bonus Coin (Level 4-4)": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level Complete (Level 4-4)": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Gem 1 (Level 4-5)": "Grapple Hook + Cannons",
    "Gem 2 (Level 4-5)": "Grapple Hook + Cannons + Wall Jump",
    "Gem 3 (Level 4-5)": "Grapple Hook + Cannons + Wall Jump + Climb + Balloons",
    "Gem 4 (Level 4-5)": "Grapple Hook + Cannons + Wall Jump + Climb",
    "Gem 5 (Level 4-5)": "Grapple Hook + Cannons + Wall Jump + Climb",
    "Bonus Coin (Level 4-5)": "Grapple Hook + Cannons + Wall Jump + Climb",
    "Level Complete (Level 4-5)": "Grapple Hook + Cannons + Wall Jump + Climb",
    "Gem 1 (Level 4-B)": "Slam + Balloons + Grapple Hook",
    "Gem 2 (Level 4-B)": "Slam + Balloons + Grapple Hook + Wall Jump",
    "Gem 3 (Level 4-B)": "Slam + Balloons + Grapple Hook + Wall Jump + Balloons",
    "Gem 4 (Level 4-B)": "Slam + Balloons + Grapple Hook + Wall Jump + Balloons",
    "Gem 5 (Level 4-B)": "Slam + Balloons + Grapple Hook + Wall Jump + Balloons",
    "Level Complete (Level 4-B)": "Slam + Balloons + Grapple Hook + Wall Jump + Balloons + Cannons",
    "Beat DRGN": "Slam + Balloons + Grapple Hook + Wall Jump + Balloons + Cannons",
    "Gem 1 (Bonus 4-1)": "Grapple Hook + Wall Jump || Slam",
    "Gem 2 (Bonus 4-1)": "Grapple Hook + Wall Jump || Slam",
    "Gem 3 (Bonus 4-1)": "Grapple Hook + Wall Jump || Slam",
    "Gem 1 (Bonus 4-2)": "Cannons + Grapple Hook + Wall Jump + Slam",
    "Gem 2 (Bonus 4-2)": "Cannons + Grapple Hook + Wall Jump + Slam",
    "Gem 3 (Bonus 4-2)": "Cannons + Grapple Hook + Wall Jump + Slam",
    "Gem 1 (Bonus 4-3)": "Bounce Pads + Wall Jump + Grapple Hook + Slam",
    "Gem 2 (Bonus 4-3)": "Bounce Pads + Wall Jump + Grapple Hook + Slam",
    "Gem 3 (Bonus 4-3)": "Bounce Pads + Wall Jump + Grapple Hook + Slam",
    "Gem 1 (Bonus 4-4)": "Cannons + Grapple Hook",
    "Gem 2 (Bonus 4-4)": "Cannons + Grapple Hook",
    "Gem 3 (Bonus 4-4)": "Cannons + Grapple Hook",
    "Gem 1 (Level 5-1)": "Cannons + Grapple Hook + Wall Jump",
    "Gem 2 (Level 5-1)": "Cannons + Grapple Hook + Wall Jump + Slam",
    "Gem 3 (Level 5-1)": "Cannons + Grapple Hook + Wall Jump + Slam + Bounce Pads || Damage Boost + Balloons",
    "Gem 4 (Level 5-1)": "Cannons + Grapple Hook + Wall Jump + Slam + Bounce Pads || Damage Boost + Balloons",
    "Gem 5 (Level 5-1)": "Cannons + Grapple Hook + Wall Jump + Slam + Bounce Pads || Damage Boost + Balloons",
    "Bonus Coin (Level 5-1)": "Cannons + Grapple Hook + Wall Jump + Slam",
    "Level Complete (Level 5-1)": "Cannons + Grapple Hook + Wall Jump + Slam + Bounce Pads || Damage Boost + Balloons",
    "Gem 1 (Level 5-2)": "Grapple Hook + Wall Jump + Swim + Slam + Balloons",
    "Gem 2 (Level 5-2)": "Grapple Hook + Wall Jump + Swim + Slam + Balloons + Cannons",
    "Gem 3 (Level 5-2)": "Grapple Hook + Wall Jump + Swim + Slam + Balloons + Cannons",
    "Gem 4 (Level 5-2)": "Grapple Hook + Wall Jump + Swim + Slam + Balloons + Cannons",
    "Gem 5 (Level 5-2)": "Grapple Hook + Wall Jump + Swim + Slam + Balloons + Cannons",
    "Bonus Coin (Level 5-2)": "Grapple Hook + Wall Jump + Swim + Slam + Balloons + Cannons",
    "Level Complete (Level 5-2)": "Grapple Hook + Wall Jump + Swim + Slam + Balloons + Cannons",
    "Gem 1 (Level 5-3)": "Bounce Pads + Balloons + Grapple Hook + Wall Jump",
    "Gem 2 (Level 5-3)": "Bounce Pads + Balloons + Grapple Hook + Wall Jump",
    "Gem 3 (Level 5-3)": "Bounce Pads + Balloons + Grapple Hook + Wall Jump",
    "Gem 4 (Level 5-3)": "Bounce Pads + Balloons + Grapple Hook + Wall Jump",
    "Gem 5 (Level 5-3)": "Bounce Pads + Balloons + Grapple Hook + Wall Jump",
    "Bonus Coin (Level 5-3)": "Bounce Pads + Balloons + Grapple Hook + Wall Jump",
    "Level Complete (Level 5-3)": "Grapple Hook + Wall Jump + Swim + Slam + Balloons + Cannons",
    "Gem 1 (Level 5-4)": "Balloons + Grapple Hook",
    "Gem 2 (Level 5-4)": "Balloons + Grapple Hook",
    "Gem 3 (Level 5-4)": "Balloons + Grapple Hook + Cannons",
    "Gem 4 (Level 5-4)": "Balloons + Grapple Hook + Cannons + Bounce Pads",
    "Gem 5 (Level 5-4)": "Balloons + Grapple Hook + Cannons + Bounce Pads",
    "Bonus Coin (Level 5-4)": "Balloons + Grapple Hook",
    "Level Complete (Level 5-4)": "Balloons + Grapple Hook + Cannons + Bounce Pads",
    "Gem 1 (Level 5-5)": "Wall Jump + Grapple Hook + Balloons",
    "Gem 2 (Level 5-5)": "Wall Jump + Grapple Hook",
    "Gem 3 (Level 5-5)": "Wall Jump + Grapple Hook + Balloons",
    "Gem 4 (Level 5-5)": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Gem 5 (Level 5-5)": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Level Complete (Level 5-5)": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Beat REX V2": "Wall Jump + Grapple Hook + Balloons + Cannons",
    "Gem 1 (Level 5-B)": "Bounce Pads + Cannons + Wall Jump + Grapple Hook",
    "Gem 2 (Level 5-B)": "Bounce Pads + Cannons + Wall Jump + Grapple Hook + Climb + Carrots",
    "Gem 3 (Level 5-B)": "Bounce Pads + Cannons + Wall Jump + Grapple Hook + Climb + Bounce Pads + Swim",
    "Gem 4 (Level 5-B)": "Bounce Pads + Cannons + Wall Jump + Grapple Hook + Climb + Bounce Pads + Swim",
    "Gem 5 (Level 5-B)": "Bounce Pads + Cannons + Wall Jump + Grapple Hook + Climb + Bounce Pads + Swim",
    "Level Complete (Level 5-B)": "Bounce Pads + Cannons + Wall Jump + Grapple Hook + Climb + Bounce Pads + Swim",
    "Beat MECH": "Bounce Pads + Cannons + Wall Jump + Grapple Hook + Climb + Bounce Pads + Swim",
    "Defeat NUL": "Bounce Pads + Cannons + Wall Jump + Grapple Hook + Climb + Bounce Pads + Swim",
    "Gem 1 (Bonus 5-1)": "Grapple Hook + Balloons + Slam + Cannons + Bounce Pads",
    "Gem 2 (Bonus 5-1)": "Grapple Hook + Balloons + Slam + Cannons + Bounce Pads",
    "Gem 3 (Bonus 5-1)": "Grapple Hook + Balloons + Slam + Cannons + Bounce Pads",
    "Gem 1 (Bonus 5-2)": "Grapple Hook + Wall Jump",
    "Gem 2 (Bonus 5-2)": "Grapple Hook + Wall Jump",
    "Gem 3 (Bonus 5-2)": "Grapple Hook + Wall Jump",
    "Gem 1 (Bonus 5-3)": "Slam + Grapple Hook + Wall Jump",
    "Gem 2 (Bonus 5-3)": "Slam + Grapple Hook + Wall Jump",
    "Gem 3 (Bonus 5-3)": "Slam + Grapple Hook + Wall Jump",
    "Gem 1 (Bonus 5-4)": "Grapple Hook",
    "Gem 2 (Bonus 5-4)": "Grapple Hook",
    "Gem 3 (Bonus 5-4)": "Grapple Hook",
    "Gem 1 (Level 6-1)": "Grapple Hook + Balloons + Cannons + Wall Jump + Slam",
    "Gem 2 (Level 6-1)": "Grapple Hook + Balloons + Cannons + Wall Jump + Slam",
    "Gem 3 (Level 6-1)": "Grapple Hook + Balloons + Cannons + Wall Jump + Slam",
    "Gem 4 (Level 6-1)": "Grapple Hook + Balloons + Cannons + Wall Jump + Slam",
    "Gem 5 (Level 6-1)": "Grapple Hook + Balloons + Cannons + Wall Jump + Slam",
    "Gem 1 (Level 6-2)": "Grapple Hook + Bounce Pads + Cannons",
    "Gem 2 (Level 6-2)": "Grapple Hook + Bounce Pads + Cannons + Wall Jump",
    "Gem 3 (Level 6-2)": "Grapple Hook + Bounce Pads + Cannons + Wall Jump + Slam",
    "Gem 4 (Level 6-2)": "Grapple Hook + Bounce Pads + Cannons + Wall Jump + Slam",
    "Gem 5 (Level 6-2)": "Grapple Hook + Bounce Pads + Cannons + Wall Jump + Slam",
    "Gem 1 (Level 6-3)": "Grapple Hook + Wall Jump",
    "Gem 2 (Level 6-3)": "Grapple Hook + Wall Jump + Bounce Pads + Slam + Balloons || Damage Boost",
    "Gem 3 (Level 6-3)": "Grapple Hook + Wall Jump + Bounce Pads + Slam + Balloons + Cannons + Swim",
    "Gem 4 (Level 6-3)": "Grapple Hook + Wall Jump + Bounce Pads + Slam + Balloons + Cannons + Swim",
    "Gem 5 (Level 6-3)": "Grapple Hook + Wall Jump + Bounce Pads + Slam + Balloons + Cannons + Swim",
    "Gem 1 (Bonus 6-1)": "Wall Jump + Balloons + Slam + Swim",
    "Gem 2 (Bonus 6-1)": "Wall Jump + Balloons + Slam + Swim",
    "Gem 3 (Bonus 6-1)": "Wall Jump + Balloons + Slam + Swim",
    "Gem 1 (Bonus 6-2)": "Cannons + Balloons + Grapple Hook + Bounce Pads + Wall Jump",
    "Gem 2 (Bonus 6-2)": "Cannons + Balloons + Grapple Hook + Bounce Pads + Wall Jump",
    "Gem 3 (Bonus 6-2)": "Cannons + Balloons + Grapple Hook + Bounce Pads + Wall Jump",
    "Gem 1 (Bonus 6-3)": "Grapple Hook",
    "Gem 2 (Bonus 6-3)": "Grapple Hook",
    "Gem 3 (Bonus 6-3)": "Grapple Hook",

    "Pet The Dog": "Grapple Hook + Bounce Pads + Balloons + Cannons + Wall Jump + Climb + Swim + Slam"
  }
}